# Site
repository: sahinyyurt/sahinyyurt.github.io
favicon: images/favicon.ico

# Personal info
name: Şahin YEŞİLYURT
title: Senior Software Engineer
email: sahinyesilyurt@gmail.com
website: sahinyesilyurt.com

# Social links
twitter_username: sahinyesilyurt
github_username:  sahinyyurt
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sahinyeslyurt
linkedin_username: sahinyesilyurt
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Şahin and I'm a senior software engineer.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
